### ISSUE TITLE
Database structure 

### ISSUE THREAD

**Issue by awadhesh39** [salahatwa/Hospital-Management-System#1]
Ca you describe database structure

**Comment by enriqueortegagarcia** [comment]
Would love so much to have available a PL/SQL script in order to build Oracle_11g database structure,
possible usernames to set up and the PORTS-Connectivity with Oracle issues solved in order to make all finally work fine.  I have been able to compile,solve +700 errors on Eclipse Jave EE IDE, set the Tomcat server and make the website appear on Firefox at localhost:8080.
I fear I am asking too much!!??.  Please answer.

**Comment by AsickAhamed** [comment]
post the database file

**Comment by salahatwa** [comment]
Database script uploaded .
